Home Page Responsiveness + Sample Census Formatting
codeforsanjose/census2020 pull request #103
Opened 2019-12-07 00:37 UTC by ianHunterClipd

Hey all, I am working on issues #78 and #73 and was hoping to get some feedback on the code before I proceed. 

Re: responsiveness - I am controlling what is presented by doing direct comparisons with window.innerWidth (example in DetailViewContainer.js, lines 356 - 396). Is this a valid approach or would you recommend some other strategy? 

Re: formatting the census question subtexts. I am unclear on when / where I should be using the FormattedMarkdownMessage. I played with the component and was able to get it to render some markdown but I feel like I am missing something. Any comments on SampleCensus.js and the definition of the questions array (starts @ line 10) would be appreciated.

2019-12-07 00:41 UTC, ianHunterClipd commented on client/components/DetailViewContainer.js
> +          { screen_width < 800 && (
This is an example of my comparisons with window.innerWidth (saved locally as screen_width) for responsiveness.

2019-12-07 01:11 UTC, JMStudiosJoe requested changes
looks good so far only need to remove logs.

2019-12-07 01:11 UTC, JMStudiosJoe commented on client/components/FormattedMarkdownMessage.js
> +  console.log(values)
remove the logs please unless needed there for debugging?

2019-12-07 02:36 UTC, turnerhayes commented
The ideal approach to responsiveness is using CSS with [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries); these let you apply certain styles only if certain conditions are met (e.g. the device width is > 800px). This is better from both a separation of concerns perspective, and, I think, from a performance perspective (I am under the impression that applying new styles is generally less expensive than manipulating DOM).it 

As for FormattedMarkdownMessage, unfortunately there are some caveats to using it, due to the markdown parsing library we're using (I describe them in #98). Use it in cases where the content you're rendering is already meant to be displayed as a paragraph (or series of paragraphs); e.g. good for FAQ answers, not good for headers.

2019-12-07 02:39 UTC, turnerhayes commented on client/components/DetailViewContainer.js
> +        `${top_reasons_class}__${size}`,
Good application of BEM! One minor thing, the "official" [BEM specs](http://getbem.com/naming/) use `--` as a separator for modifiers like ${size}. You could change this to `${top_reasons_class}--${size}`.

2019-12-07 02:41 UTC, turnerhayes commented on client/components/SampleCensus.js
> +        { /*<FormattedMarkdownMessage
Remove commented out code

2019-12-07 02:45 UTC, turnerhayes approved these changes
I'm okay with this going through as is, but a couple of things:

* It would be better to use media queries for the responsiveness; if you change the DOM or inline styles, React will rerender the subtree, which we want to minimize. If you use CSS, the DOM doesn't have to change when screen size changes.
* I would prefer to have the content stuff (sample census) be in their on PR, if that wouldn't be too difficult.

2019-12-08 18:15 UTC, ianHunterClipd commented
@turnerhayes 
Re media queries - got it. 

Re sample census - I'll remove the existing two questions from the sample census from this PR and move them into a new one.

2019-12-08 23:19 UTC, JMStudiosJoe approved these changes

2019-12-08 23:19 UTC, merged